[IV-24-25] Envio Objetivo 0
mmnuria/PersonalSportCalendary pull request #1
Opened 2024-09-20 11:47 UTC by mmnuria

* [ VERDADERO] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [VERDADERO] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
* [ VERDADERO ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
* [ VERDADERO] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
* [ VERDADERO] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
* [VERDADERO ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?

2024-09-22 10:26 UTC, JJ commented
> * [ VERDADERO] ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [VERDADERO] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
> 
>     * [ VERDADERO ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
> 
>     * [ VERDADERO] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
> 
>     * [ VERDADERO] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
> 
>     * [VERDADERO ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?

Con que pongas un :heavy_check_mark: es suficiente.

2024-09-22 10:28 UTC, JJ reviewed
Debes describir un problema, no una aplicación. La aplicación que se haga se tiene que ir decidiendo a través de una metodología. Si lo que estás contando aquí fue lo que se te validó en el juego de rol, quizás sería conveniente que comenzaras de nuevo en la clase del jueves (o por tu cuenta)

2024-09-22 10:28 UTC, JJ commented on README.md
> +Esta aplicacion va dirigida a personas muy ocupadas en su dia a dia como madres, padres, empresarios, etc. Adultos en general que no consiguen organizar su tiempo libre y termina convirtiendose en ti
Si empiezas por "esta aplicación" no estás describiendo un problema. Como pone en [el resumen](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#tldr), se tiene que...

> Pensar en un problema a resolver

2024-09-23 07:12 UTC, mmnuria commented
En clase propuse el problema suponiendo que soy una madre con ciertos problemas y eso fue lo que se me validó. Si me lo permite puedo modificar el readme explicando solamente el problema,  porque sin querer mezclé el problema con la resolución.

2024-09-23 08:00 UTC, JJ commented
> En clase propuse el problema suponiendo que soy una madre con ciertos problemas y eso fue lo que se me validó. Si me lo permite puedo modificar el readme explicando solamente el problema, porque sin querer mezclé el problema con la resolución.

Puedes modificar lo que quieras las veces que quieras.

2024-09-23 09:05 UTC, mmnuria commented
@JJ ya lo he modificado, estoy a la espera de revisión. Gracias.

2024-09-23 09:15 UTC, JJ commented
> * [ VERDADERO] ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [VERDADERO] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
> 
>     * [ VERDADERO ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
> 
>     * [ VERDADERO] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

No lo has incluido. Por favor, hazlo (y no respondas a una pregunta  positivamente si no la entiendes o no lo has hecho; el que pase el objetivo o no va a depender de lo que marques, se trata simplemente de ahorrarnos a los dos trabajo)

Adicionalmente, aunque efectivamente enuncias un problema y en ese sentido estaría bien, no estoy tan seguro de que cumpla el resto de las condiciones, como por ejemplo que tengas todos los datos necesarios para solucionarlo. ¿Tienes en algún lado o puedes conseguir una lista de ejercicios y el tiempo que tarda cada uno? ¿Esos ejercicios están cualificados por grupo muscular o dificultad?

Ten en cuenta que esto es un proyecto que vas a tener que llevar a cabo el resto del cuatrimestre. Tener descrito un problema de forma válida es el primer paso, pero no debemos olvidar que hay que trabajar con esto y poder salir adelante. 

Mira lo que dice [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio)

> En este objetivo no se pide que se especifique la solución al problema. Sin embargo, sí habrá que hacerlo más adelante y si se trata de un problema cuyas posibles soluciones no sean válidas para esta asignatura, se rechazará en este objetivo. Por eso hay que pensar en la solución al problema, y en caso de que no quede claro su entidad por la sola descripción del mismo, especificarlo.

Creo que sería tu caso. Incluso así tendrías que tener en cuenta que la lista de ejercicios, la progresión, el calentamiento si fuera necesario y todos esos datos tendrías que tenerlos tú  y procesarlos para añadir valor a lo que vayas a aportar a la clienta.

2024-09-23 09:52 UTC, mmnuria commented
En cuanto a los ejercicios en principio tengo en mente de tener los datos suficientes, clasificándolos por tipos de materiales a necesitar, ya que, es un problema orientado a el ejercicio de mantenimiento desde casa, de manera general, abarcando todo tipos de ejercicios musculares. Básicamente, serán ejercicios físicos sencillos, que ayuden a que esas personas que no tienen tiempo se mantengan activas sin necesitar grandes horas en un gimnasio y con materiales que tengan en casa, es por ello que, de esa manera se clasificaran los ejercicios.

Los únicos datos que se necesitaran por parte de los usuarios es su disponibilidad y utensilios que poseen en casa.

2024-09-23 09:58 UTC, mmnuria commented
[ ✔️] ¿Se trata de un problema real del que se tenga conocimiento personal? Correcto ya que, yo tuve ese mismo problema y realizo ejercicio físico desde casa haciendo una labor extra por aprender que son los utensilios básicos para ello.

[✔️] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube? Correcto, ya que para la resolución del problema hay que tener en cuenta datos e información previamente integrada.

[ ✔️ ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando? Si, ya que aportan el valor de gestión del tiempo por parte de nuestro publico objetivo, sin necesidad de requerir materiales muy sofisticados.

[ ✔️] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el README? Si.

[ ✔️] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
Si, poseo todos los ejercicios en una base de datos en la que clasificaré por tipo de materiales a necesitar, ya que todo está orientado a la actividad física para el mantenimiento físico, sin cuestiones como grupos musculares, ni nada. Solamente depende del tipo de material que poseas, así serán los ejercicios que se te ofrece.

[✔️ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo? La he seguido paso a paso.

2024-09-24 08:38 UTC, mmnuria commented
@JJ esperando revision

2024-09-24 11:35 UTC, JJ commented
Por favor, poned la lista de comprobación en el cuerpo, no en un comentario.

2024-09-24 11:36 UTC, JJ commented
> En cuanto a los ejercicios en principio tengo en mente de tener los datos suficientes, clasificándolos por tipos de materiales a necesitar, ya que, es un problema orientado a el ejercicio de mantenimiento desde casa, de manera general, abarcando todo tipos de ejercicios musculares. Básicamente, serán ejercicios físicos sencillos, que ayuden a que esas personas que no tienen tiempo se mantengan activas sin necesitar grandes horas en un gimnasio y con materiales que tengan en casa, es por ello que, de esa manera se clasificaran los ejercicios.
> 
> Los únicos datos que se necesitaran por parte de los usuarios es su disponibilidad y utensilios que poseen en casa.

Cualquier explicación la tienes que hacer en el README, no en un comentario. Lo que pones en el README se queda en el repositorio.

2024-09-24 11:39 UTC, JJ requested changes
Por favor, revisa también la [guía del objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) que dice:

> Creación de par de claves (pública/privada) y subida de clave pública a GitHub.

También está en la lista de comprobación. Si no entiendes alguno de los apartados, o no entiendes por qué se te solicita eso, lo mejor es preguntar, no marcarlo o las dos cosas.

2024-09-24 11:39 UTC, JJ commented on README.md
> +Madres, padres y personas adultas con una alta carga de trabajo diario, enfrentan el reto de equilibrar sus múltiples responsabilidades (trabajo, cuidado de sus hijos, desplazamientos,etc). A pesar d
Estás expresando un deseo, no una necesidad. Es difícil o imposible crear un programa para satisfacer un deseo, que además es físico.

2024-09-26 07:01 UTC, mmnuria commented
@JJ Solicito revisión, he añadido lo que me faltaba:

1. Creación de par de claves (pública/privada) y subida de clave pública a GitHub.
2. Configuración correcta de nombre y correo electrónico para los commits.
3. Creación archivo .gitignore
4. Describir correctamente el problema en README.md

2024-09-26 15:20 UTC, JJ approved these changes
:+1:

2024-09-26 18:29 UTC, merged