[IV-24-25] Objetivo3
mmnuria/PersonalSportCalendary pull request #19
Opened 2024-12-15 13:47 UTC by mmnuria

* [x] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x] ¿Ese issue está asignado a un milestone?
* [x] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [x] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [x] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [x] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2024-12-15 14:05 UTC, mmnuria commented
@JJ listo para revisión

2024-12-15 16:51 UTC, JLombar reviewed
Buenas, te he dejado unos comentarios para ayudar con el objetivo. Está muy completo pero lo más importante es la elección correcta de requisitos y en tu caso están regular, pero está bien enfocado el resto del trabajo. Otra cosa importante es ajustarse a hablar sólamente de los requisitos, cualquier otra cosa está mal. Si quieres hablar de más características añádelas como requisitos.  
Si quieres cuando acabes pideme revisión y le damos otro repaso :)

2024-12-15 16:51 UTC, JLombar commented on README.md
> +Para una información mucho más completa y detallada puede leer el siguiente [documento](./docs/gestor_dependencias.md).
Ya que pones esto aquí, podrías decir que gestor de dependencias usas en el README

2024-12-15 16:51 UTC, JLombar commented on docs/gestor_dependencias.md
> +### Gestión de dependencias en Go
Este archivo está muy completo, no tengo nada que añadir más que quizás podrías enlazar algún link a la documentación oficial o algo así de donde has obtenido esta información

2024-12-15 16:51 UTC, JLombar commented on docs/gestor_tareas.md
> +- **Actualización constante**: La herramienta debe contar con soporte activo y actualizaciones regulares para evitar problemas de compatibilidad.
De donde sacas esta información? GitHub? Podrías indicarlo para que se pueda contrastar que es cierto

2024-12-15 16:51 UTC, JLombar commented on docs/gestor_tareas.md
> +- **Promoción de buenas prácticas**: Debe alinearse con las características y necesidades del ecosistema Go, facilitando la adopción de patrones estándar.
Esto es un criterio obvio y ya lo indica el guión, creo que es innecesario

2024-12-15 16:51 UTC, JLombar commented on docs/gestor_tareas.md
> +- **Facilidad de uso**: Una sintaxis intuitiva es esencial para que los desarrolladores puedan aprender y usar la herramienta rápidamente, reduciendo curvas de aprendizaje innecesarias.
Los criterios deben ser objetivos, la facilidad es algo bastante subjetivo

2024-12-15 16:51 UTC, JLombar commented on docs/gestor_tareas.md
> +- **Minimización de deuda técnica**: Cada funcionalidad debe estar diseñada para evitar configuraciones complicadas y garantizar que las tareas no introduzcan riesgos de mantenimiento a largo plazo.
Esto no viene a ser lo mismo que el primer requisito? quizás podrías eliminar uno o fusionarlos

2024-12-15 16:51 UTC, JLombar commented on docs/gestor_tareas.md
> +- **Ejemplo de uso**:
En ningún momento se pide ejemplos de uso en el objetivo. Sé que puede ser molesto tener que borrarlos después de haberlos hecho, pero no añade nada a la elección de la herramienta, que es para lo que existe únicamente este documento

2024-12-16 16:01 UTC, hossam1522 reviewed
Buenas! Aparte de lo mencionado por el compañero, te dejo un par de comentarios también. ¡Ánimo!

2024-12-16 16:01 UTC, hossam1522 commented on docs/gestor_tareas.md
> +Para seleccionar la herramienta más adecuada en la gestión de tareas en este proyecto, evaluaremos y compararemos cada una de las opciones disponibles con base en los criterios establecidos previamen
Realmente, como dice el compañero, creo que lo relevante para este objetivo empieza a partir de aquí. Tienes que tomar una decisión y justificarla, no explicar a fondo ni con ejemplos cada una de las opciones.

2024-12-17 16:22 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Facilidad de uso**: Una sintaxis intuitiva es esencial para que los desarrolladores puedan aprender y usar la herramienta rápidamente, reduciendo curvas de aprendizaje innecesarias.
El requisito de que la sintaxis sea lo más amigable posible no considero que sea objetiva, por ello más abajo ejemplifico los casos de uso para cada herramienta y que al seleccionar la herramienta, se vea objetivamente que lo cumple.

2024-12-17 16:27 UTC, JJ commented on docs/gestor_tareas.md
> +- **Facilidad de uso**: Una sintaxis intuitiva es esencial para que los desarrolladores puedan aprender y usar la herramienta rápidamente, reduciendo curvas de aprendizaje innecesarias.
Nuria, por favor. O son objetivos o no lo son. También deben ser *simples*. Si tienes que ir mirando a casos de uso, ¿te parece simple?

2024-12-17 16:38 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Facilidad de uso**: Una sintaxis intuitiva es esencial para que los desarrolladores puedan aprender y usar la herramienta rápidamente, reduciendo curvas de aprendizaje innecesarias.
Perdona, me referia a que no considero que sean subjetivos, pero segun me menciona ahora, es cierto que no es algo tan simple, ya que, hay que ir comprobandolo uno a uno. Procedo a eliminarlo ya que no cumple con ser simple.

2024-12-17 16:50 UTC, mmnuria commented
@JLombar y @hossam1522 he añadido cambios en función de vuestras sugerencias. Muchas gracias de antemano, en cuanto os parezca correcto, menciono al profesor.

2024-12-17 20:16 UTC, JLombar reviewed
Vas muy bien, pero la parte más importante de esto objetivo (y casi que de todos a partir de este) es la documentación, sobre todo la elección de unos criterios correctos.

Ha mejorado mucho pero necesita otro repasillo, dale otra vuelta. Suerte!

2024-12-17 20:16 UTC, JLombar commented on docs/gestor_tareas.md
> +- **Documentación y comunidad**: Es importante que la herramienta tenga una base sólida de documentación y soporte comunitario para resolver problemas y extender funcionalidades.
Cómo evaluas la comunidad o la documentación? Creo que sigue siendo un criterio regulero a la hora de escoger la herramienta

2024-12-17 20:16 UTC, JLombar commented on docs/gestor_tareas.md
> +- **Actualización constante y minimización de deuda técnica**: La herramienta debe contar con soporte activo y actualizaciones regulares que aseguren su compatibilidad, mientras cada funcionalidad se
Como aseguras que una herramienta va a hacer esto?
> que aseguren su compatibilidad, mientras cada funcionalidad se diseña para evitar configuraciones complejas

El criterio como tal está bien, pero esta parte de la explicación creo que deberías omitirla, con una actualización constante no te aseguras que no vaya a tener una sintaxis compleja (por cierto, que tenga una sintaxis compleja no creo que sea algo muy objetivo)

2024-12-17 20:16 UTC, JLombar commented on docs/gestor_tareas.md
> +   - **Just** es la opción más sólida, ya que cuenta con actualizaciones constantes, una comunidad activa que asegura su desarrollo y soporte, y una sintaxis simple que evita configuraciones compleja
Es importante a la hora de evaluar un criterio que esa evaluación se limite a dicho criterio. Si este criterio va de actualizaciones no creo que debas hablar de comunidad (más cuando lo tienes como un criterio a parte), además la sintaxis no tiene nada que ver con tu criterio (por no decir que es algo subjetivo)

2024-12-17 20:16 UTC, JLombar commented on docs/gestor_tareas.md
> +- Respecto a la **documentación y comunidad**
Como ya te he dicho arriba, creo que esta parte deberías modficarla con un mejor criterio

2024-12-18 11:26 UTC, hossam1522 reviewed
En principio no tengo nada que añadir a lo comentado por el compañero. Si resuelves sus comentarios, por mi parte lo veo aprobado.

2024-12-18 18:51 UTC, mmnuria commented
@JLombar y @hossam1522 ya he realizado los cambios. Espero vuestro feedback. Muchas gracias por vuestras correcciones!

2024-12-19 07:13 UTC, JLombar commented
@mmnuria te vuelvo a repetir que no sé como evaluas una documentación que sea mejor o peor. ¿Cómo lo haces? ¿Cuentas el número de ejemplo? ¿O cómo valoras el ejemplo?

Yo creo que deberías modificarlo, igualmente si piensas que está bien pídele revisión a Juan

2024-12-19 07:20 UTC, mmnuria commented
> @mmnuria te vuelvo a repetir que no sé como evaluas una documentación que sea mejor o peor. ¿Cómo lo haces? ¿Cuentas el número de ejemplo? ¿O cómo valoras el ejemplo?
> 
> Yo creo que deberías modificarlo, igualmente si piensas que está bien pídele revisión a Juan

Como puede ver en mi ultimo commit, lo he cambiado, ahora establezco que el soporte se verifica con la cantidad de issue resueltos en el ultimo mes, de la misma forma eso nos muestra la comunidad activa que posee la herramienta. Aunque es cierto que la parte de la documentación sigue siendo un poco subjetiva. Eliminaré esa parte en concreto.

2024-12-19 07:23 UTC, mmnuria commented
@JLombar ahora creo que ya está correcto. Ahora me dices que te parece y paso a mencionar al profesor.

2024-12-19 08:30 UTC, JLombar approved these changes

2024-12-19 08:51 UTC, hossam1522 commented
> Como puede ver en mi ultimo commit, lo he cambiado, ahora establezco que el soporte se verifica con la cantidad de issue resueltos en el ultimo mes, de la misma forma eso nos muestra la comunidad activa que posee la herramienta. Aunque es cierto que la parte de la documentación sigue siendo un poco subjetiva. Eliminaré esa parte en concreto.

No creo que la cantidad de issues resueltas dé una idea clara de si la comunidad es activa o no. Por ejemplo, si un repositorio tiene 500 issues cerradas pero lleva sin cerrar ninguna 2 años no es más activo que un repositorio que resuelva issues cada dos días y solo tenga 100 cerradas.

Además, no sé hasta qué punto cerrar issues o no se considera comunidad activa. Creo que no es demasiado lógico decir que Make no tiene una comunidad activa cuando se sigue mencionando día a día en muchos foros. 

Además, el repositorio de Make no es ese, sino este:

- http://git.savannah.gnu.org/cgit/make.git

Donde, como puedes ver, el último commit es de hace 10 días.

2024-12-19 08:52 UTC, hossam1522 commented on docs/gestor_tareas.md
> +[Documentación oficial de Make](https://github.com/wkusnierczyk/make?tab=readme-ov-file)
En base a lo dicho, ese no es el repositorio, sino:

- http://git.savannah.gnu.org/cgit/make.git

2024-12-19 08:52 UTC, hossam1522 commented on docs/gestor_tareas.md
> +  - **Sage**: Al ser relativamente nuevo, el repositorio tiene una comunidad en crecimiento, con pocos *issues* resueltos hasta ahora.
Lo que te he comentado en el mensaje de arriba.

2024-12-20 11:21 UTC, mmnuria commented
@JJ solicito revision

2024-12-20 11:36 UTC, mmnuria commented
@JJ solicito revision

2024-12-20 12:15 UTC, JJ reviewed
Dale un pequeña vuelta; está bastante cerca, pero tienes que ser un poco más precisa en los criterios que sigues y en cómo las herramientas listadas cumplen esos criterios.

2024-12-20 12:15 UTC, JJ commented on docs/gestor_dependencias.md
> +### Gestión de dependencias en Go
Di donde lo has resuelto.

2024-12-20 12:15 UTC, JJ commented on docs/gestor_tareas.md
> +Para garantizar un flujo de trabajo eficiente y mantener la calidad del proyecto, es crucial seleccionar una herramienta que sea adecuada para el desarrollo con Go. Los criterios seleccionados son:
¿Crees que aporta algo este párrafo?

2024-12-20 12:15 UTC, JJ commented on docs/gestor_tareas.md
> +- **Actualización constante y minimización de deuda técnica**: La herramienta debe contar con soporte activo y actualizaciones regulares, para reducir riesgos de mantenimiento a largo plazo.
Si las unes en una sola porque te lo ha pedido un compañero, usa un lenguaje preciso para indicar que son una sola cosa, o una consecuencia de la otra, y no dos cosas unidas por una conjunción *y*. Así demuestras que entiendes por qué los has juntado y qué relación hay entre los dos conceptos.

2024-12-20 12:15 UTC, JJ commented on docs/gestor_tareas.md
> +Para garantizar un flujo de trabajo eficiente y mantener la calidad del proyecto, es crucial seleccionar una herramienta que sea adecuada para el desarrollo con Go. Los criterios seleccionados son:
(Es solo un criterio, además)

2024-12-20 12:15 UTC, JJ commented on docs/gestor_tareas.md
> +Make es una herramienta ampliamente utilizada para la automatización de tareas, soportada de forma robusta en muchos lenguajes y entornos. Su uso en proyectos Go puede ser más complicado debido a la
Si no está relacionado con los criterios, ¿crees que esta descripción aporta algo?

2024-12-20 12:15 UTC, JJ commented on docs/gestor_tareas.md
> +Just ofrece una alternativa más sencilla y enfocada, ideal para proyectos Go. Su diseño simple y directo favorece la definición de tareas sin complicar la estructura ni requerir el manejo explícito d
¿Más sencilla que qué? ¿Es un factor la sencillez?

2024-12-20 12:15 UTC, JJ commented on docs/gestor_tareas.md
> +Task utiliza un enfoque basado en archivos YAML para definir tareas. Aunque es potente, esta configuración puede ser innecesariamente compleja para proyectos más simples.
¿Te sirven para tomar la decisión o para que yo entienda la decisión que has tomado?

2024-12-20 12:15 UTC, JJ commented on justfile
> +	go fmt {{pkg}}
¿Esto verifica *solo* la sintaxis o hace algo más?

2024-12-23 10:24 UTC, mmnuria commented on docs/gestor_tareas.md
> +Para garantizar un flujo de trabajo eficiente y mantener la calidad del proyecto, es crucial seleccionar una herramienta que sea adecuada para el desarrollo con Go. Los criterios seleccionados son:
Prescindiré de el, es cierto que no aporta nada.

2024-12-23 10:29 UTC, mmnuria commented on docs/gestor_tareas.md
> +Make es una herramienta ampliamente utilizada para la automatización de tareas, soportada de forma robusta en muchos lenguajes y entornos. Su uso en proyectos Go puede ser más complicado debido a la
En esta parte el objetivo es introducir la herramienta de una forma reducida, además de destacar diferentes aspectos de esta con su enlace a la documentación oficial. En el siguiente apartado, se pone en comparativa cada una de ellas con los criterios que se han seleccionado, de forma que, de llega a la conclusión de que herramienta se ha escogido.

2024-12-23 10:31 UTC, mmnuria commented on docs/gestor_tareas.md
> +Just ofrece una alternativa más sencilla y enfocada, ideal para proyectos Go. Su diseño simple y directo favorece la definición de tareas sin complicar la estructura ni requerir el manejo explícito d
Anteriormente, unos de mis criterios era el de sencillez, pero por motivos de subjetividad se decidió suprimir. Modificaré esta parte para que se ajuste mejor a lo nuevo.

2024-12-23 10:34 UTC, mmnuria commented on docs/gestor_tareas.md
> +Task utiliza un enfoque basado en archivos YAML para definir tareas. Aunque es potente, esta configuración puede ser innecesariamente compleja para proyectos más simples.
Viendo las opciones y la forma en como se definen las tareas, esta opción me parece mucho más complicada que otras herramientas como make o just, ya que estas son muy similares. Es por ello que, el uso de archivos YAML para definir las tareas no es algo que esté contemplado bajo los criterios que he contemplado en el primer apartado.

2024-12-25 17:59 UTC, mmnuria commented
@JJ Solicito revisión.

2024-12-30 11:28 UTC, JJ requested changes
*Siempre* debes indicar como se ha resuelto un comentario.
Por otro lado, los últimos commits que has hecho tienen referencia a un comentario **pero no a un issue**. *Todo* el código debe referenciar a algún issue, porque debe aportar valor al cliente, no al que evalúa.

2024-12-30 11:28 UTC, JJ commented on docs/gestor_dependencias.md
> +### Gestión de dependencias en Go
Ya te dije que indicaras donde lo has resuelto.

2024-12-30 12:13 UTC, mmnuria reviewed
Se han añadido todas las referencias a los commit que resuelven cada uno de los comentarios.

2024-12-30 12:24 UTC, mmnuria commented
@JJ ya he meniconado en cada uno de los comentarios resueltos donde se han resuelto y ademas he arreglado que los ultimos commit que no referenciaban a un issue. Solicito revision

2024-12-31 08:10 UTC, JJ requested changes
Analiza en todo caso el resto de los errores comunes, y usa como referencia el guión.

2024-12-31 08:10 UTC, JJ commented on docs/gestor_tareas.md
> +- **Minimización de deuda técnica**: La herramienta debe contar con soporte activo y actualizaciones regulares, para reducir riesgos de mantenimiento a largo plazo.
¿En qué criterio práctico se traduce esto? Que además está en el guión. Lo que tenéis que hacer es tomar lo que hay en el guión y convertirlo en criterios prácticos.

2024-12-31 08:10 UTC, JJ commented on docs/gestor_tareas.md
> +- **Compatibilidad con el ecosistema Go**: La herramienta debe estar alineada con las prácticas y necesidades comunes de los proyectos desarrollados en Go, facilitando la integración sin requerir con
Por favor, lee los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-3.md#sobre-los-criterios)

> usar criterios arbitrarios que sean verdad sólo para la herramienta que hemos elegido de antemano. Por ejemplo "Compatibilidad con el lenguaje". ¿Hay algún gestor de tareas que sea incompatible con algún lenguaje?

No entiendo tampoco por qué has introducido esto en alguna de las modificaciones.

2025-01-01 12:39 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Compatibilidad con el ecosistema Go**: La herramienta debe estar alineada con las prácticas y necesidades comunes de los proyectos desarrollados en Go, facilitando la integración sin requerir con
Tiene razon, lo habia añadido para no tener solamente un criterio, pero realmente, eso no es problema. Prescindiré de este criterio

2025-01-01 12:39 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Minimización de deuda técnica**: La herramienta debe contar con soporte activo y actualizaciones regulares, para reducir riesgos de mantenimiento a largo plazo.
Cierto, se traduce en mi caso a la "actualización constante de la herramienta", como anteriormente lo mencioné, lo volveré a corregir.

2025-01-01 12:45 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Minimización de deuda técnica**: La herramienta debe contar con soporte activo y actualizaciones regulares, para reducir riesgos de mantenimiento a largo plazo.
Solucionado en el [commit](https://github.com/mmnuria/PersonalSportCalendary/pull/19/commits/e3dd7c8032a777ef1894979db85b688d9e6c8e34)

2025-01-01 12:45 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Compatibilidad con el ecosistema Go**: La herramienta debe estar alineada con las prácticas y necesidades comunes de los proyectos desarrollados en Go, facilitando la integración sin requerir con
Solucionado en el [commit](https://github.com/mmnuria/PersonalSportCalendary/pull/19/commits/e3dd7c8032a777ef1894979db85b688d9e6c8e34)

2025-01-01 12:48 UTC, mmnuria commented
@JJ ya he revisado todo el archivo de [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-3.md#sobre-los-criterios) y corregido. Cuando pueda, me dice si lo da por aprobado y puedo comenzar a trabajar en el siguiente objetivo. Feliz año.

2025-01-02 07:50 UTC, JJ reviewed
Se trata de que digáis realmente *por qué* habéis elegido algo. Elegir algo y luego poner justificaciones cambiantes según las correcciones no parece que sea la forma más eficiente de hacerlo. ¿Por qué elegiste `just`? ¿Hay criterios y razones objetivas por lo que lo hiciste? ¿La "alineación con las prácticas comunes y necesidades" es medible? ¿Es en ese sentido mejor que `make`, que aparentemente *no* lo está?

2025-01-02 15:40 UTC, mmnuria commented
> Se trata de que digáis realmente _por qué_ habéis elegido algo. Elegir algo y luego poner justificaciones cambiantes según las correcciones no parece que sea la forma más eficiente de hacerlo. ¿Por qué elegiste `just`? ¿Hay criterios y razones objetivas por lo que lo hiciste? ¿La "alineación con las prácticas comunes y necesidades" es medible? ¿Es en ese sentido mejor que `make`, que aparentemente _no_ lo está?

Tanto` just` como `make` son buenas herramientas a elegir bajo mis criterios, pero, por no elegir `make` que es una herramienta muy común (ya que me sugirió al principio del objetivo que investigase alguna más) he encontrado la opción de` just `que además para proyectos en go es muy apropiada.

Además, encontré `Mage` y `Sage`, ya que son herramientas que permiten definir tareas directamente en go, pero ambas carecen de la reducción de deuda tecnica, ya que una no tiene actualizaciones regulares y la otra es demasiado nueva.

Bajo todos estos criterios seleccioné `just` de forma que se ajusta a los criterios que establecí previamente. En ningun momento cambio correcciones para que se alineen con `just`, si no que, cada cambio lo reviso al completo y sigue siendo la mejor opción.

2025-01-02 15:44 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Actualización constante**: La herramienta debe contar con soporte activo y actualizaciones regulares, para reducir riesgos de mantenimiento a largo plazo.
He reformulado el término para transmitir mejor lo que quería expresar (el hecho de que la herramienta esté actualizada).

2025-01-02 16:23 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Actualización constante**: La herramienta debe contar con soporte activo y actualizaciones regulares, para reducir riesgos de mantenimiento a largo plazo.
Solucionado en el [commit](https://github.com/mmnuria/PersonalSportCalendary/pull/19/commits/d22431141b786025595433cf12b52709dc3a5f2e)

2025-01-02 16:23 UTC, mmnuria commented
@JJ solicito revisión.

2025-01-03 10:53 UTC, JJ commented
> > Se trata de que digáis realmente _por qué_ habéis elegido algo. Elegir algo y luego poner justificaciones cambiantes según las correcciones no parece que sea la forma más eficiente de hacerlo. ¿Por qué elegiste `just`? ¿Hay criterios y razones objetivas por lo que lo hiciste? ¿La "alineación con las prácticas comunes y necesidades" es medible? ¿Es en ese sentido mejor que `make`, que aparentemente _no_ lo está?
> 
> Tanto` just` como `make` son buenas herramientas a elegir bajo mis criterios, aunque al realizar un análisis más extenso, encontré la opción de`just`que para proyectos en go es muy apropiada.

¿Se puede medir ese "muy apropiada"? Si no se puede medir, es que no es objetivo. Y si no es objetivo, es que no has hecho el proceso de selección de la forma apropiada.
> 
> Además, encontré `Mage` y `Sage`, ya que son herramientas que permiten definir tareas directamente en go, pero ambas carecen de la posibilidad de la reducción de la deuda tecnica, ya que, una no tiene actualizaciones regulares y la otra es muy reciente.

"Reducir la deuda técnica" no es algo que se haga con una elección o no. Deuda técnica es cuando se hace alguna elección que sabes que en el futuro tienes que pagar en tiempo. Por ejemplo, elegir algo basado en estándares anteriores que acaban de cambiar y que sabes que vas a tener que cambiar en el futuro cuando el estándar se generalice o simplemente se penalice no seguir el estándar.

No es este el caso. Si `mage` y `sage`  no están actualizadas en el último año, ese es un criterior objetivo, sobre todo si no son herramientas maduras que no necesiten actualizaciones periódicas o si el estándar del lenguaje en el que se basan haya aumentado. El que no se haya actualizado no las hace automáticamente obsoletas; son obsoletas si tienen PRs que tratan de cubrir problemas de seguridad que no se hayan fusionado, por ejemplo, o simplemente si emiten warnings o algún tipo de advertencia cuando hacen *tu* trabajo. Por favor, no lancéis "deuda técnica" a troche y moche sin entender bien lo que significa o en qué contextos se debe usar.
> 
> Teniendo todo esto en cuenta, seleccioné `just` de forma que se ajuste a los criterios que establecí previamente. En ningún momento cambio correcciones para que se alineen con `just`, si no que, cada cambio lo reviso al completo y sigue siendo la mejor opción.

El único criterio que has dicho es "me pareció más apropiado". Si eliges algo y luego estableces una serie de criterios *ad hoc* estás haciendo justamente lo contrario de lo que debes hacer, que es primero establecer una serie de criterios, luego explorar, y luego elegir. Ingeniería es tomar decisiones y debes mostrar que sabes hacerlo.
> 
> En relación con lo que mencionaba de la "alineación con las prácticas comunes y necesidades" , lo he reformulado para expresar la idea que quería transmitir de forma más clara.

Si estás reformulando criterios que *no* has seguido y diciendo lo mismo con otras palabras, creo que no se está entendiendo bien lo que se busca. Has solicitado revisión y lo haré en todo caso.

2025-01-03 10:56 UTC, JJ requested changes
Nuria, no creo que la mejor forma de emplear nuestro tiempo sea solicitar revisión cuando se cambia una palabra por otra que significa lo mismo. La próxima revisión es la última oportunidad que tienes para superar este objetivo en convocatoria ordinaria, porque en todo caso no hay tiempo físico para llegar al mismo.
Si quieres comenzar con el objetivo 4, puedes hacerlo, en el momento que hayas pasado los tests del objetivo 3.

2025-01-03 10:56 UTC, JJ commented on docs/gestor_tareas.md
> +- **Herramienta actualizada**: La herramienta debe contar con soporte activo y actualizaciones regulares, para reducir riesgos de mantenimiento a largo plazo.
No entiendo como cambiar dos palabras por otras dos palabras que vienen a significar lo mismo creéis que es una forma válida de mostrar lo que habéis entendido en este objetivo.

2025-01-03 16:06 UTC, mmnuria commented
@JJ He revisado al completo los criterios de selección de la herramienta, con el fin de ser objetiva y tras esto he vuelto a analizar cada una de las herramientas. Solicito revisión.

2025-01-05 08:21 UTC, JJ requested changes
En la revisión anterior te di la ultima oportunidad para pasar en convocatoria ordinaria. En vez de arreglar los errores cometidos, introduces nuevos criterios que a su vez introducen nuevos errores, sin mirar además los errores frecuentes. Te dije que usaras los criterios *reales*, o si estos no eran objetivos, que comenzaras desde el principio el proceso de elección.  Puedes hacerlo, pero ya no corregiré más este objetivo hasta que pase la convocatoria ordinaria.

2025-01-05 08:21 UTC, JJ commented on docs/gestor_tareas.md
> +   - La herramienta debe contar con al menos 10 contribuidores activos en su repositorio oficial en los últimos 12 meses.
Estás incluyendo criterios totalmente arbitrarios para que "salga el tuyo". De los  [errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-3.md):
> usar criterios arbitrarios que sean verdad sólo para la herramienta que hemos elegido de antemano.

2025-01-05 08:21 UTC, JJ commented on docs/gestor_tareas.md
> +   - La herramienta existe desde hace más de 5 años.
Otro criterio arbitrario. En general, ¿para qué sirve una comunidad activa si no proporciona un mantenimiento regular?
"Actividad" y "regularidad" ¿te parecen criterios objetivos?

2025-01-15 10:43 UTC, juanmaaf requested changes
Buenas. Te dejo unos comentarios en cada uno de los criterios. Espero que te sirvan de ayuda para superar el objetivo. Reflexiona cada uno de forma individual.

2025-01-15 10:43 UTC, juanmaaf commented on docs/gestor_tareas.md
> +1. **Comunidad activa**:
¿Cómo de medible es la comunidad? Es un criterio totalmente subjetivo que tratas de hacer objetivo añadiendo condiciones que cumple tu herramienta. Como bien te indicó @JJ, estás incluyendo criterios para justificar una decisión que ya has realizado previamente, y eso es un error frecuente.

2025-01-15 10:43 UTC, juanmaaf commented on docs/gestor_tareas.md
> +2. **Mantenimiento regular**:
Igual que en el criterio anterior. ¿No crees que establecer el tiempo de forma arbitraria ("último año", "6 meses", "5 años") hace que el criterio sea arbitrario?  ¿Cómo de medible y comparable es la "actividad de commits"? ¿Una herramienta con commits recientes es mejor que una que lleva más tiempo desde su último commit? ¿Un "release oficial" en el último año? ¿Sabes que hay herramientas establecidas a lo largo de los años que no tienen tantas actualizaciones constantes y son usadas más que algunas modernas? Por último, el que la herramienta "exista desde hace más de 5 años" vuelve a ser un criterio totalmente arbitrario que te ayuda a justificar una decisión que has realizado previamente.

2025-01-15 10:43 UTC, juanmaaf commented on docs/gestor_tareas.md
> +   - La herramienta no debe requerir dependencias externas adicionales para funcionar en los sistemas operativos principales (Windows, macOS, Linux).
¿Qué necesidad hay de hablar de todos los sistemas operativos principales? ¿Qué SO desarrolla el proyecto de este repositorio? Si estás desarrollando el proyecto en Linux o macOS, con este criterio buscas descartar por ejemplo Make de forma arbitraria y sin justificación alguna.

2025-01-17 12:12 UTC, mmnuria commented
Siguiendo las recomendaciones de todos mis compañeros, he modificado y corregido todo para evitar arbitrariedad o subjetividad. @JJ solicito revision.

2025-01-17 13:06 UTC, JJ commented
¿Te parece que esperemos hasta que ellos lo aprueben? Al fin y al cabo, ellos son los que tienen que decidir si los cambios que han hecho son correctos o no.
Por lo pronto, no veo muy correcto que repitas dos veces el mismo mensaje de commit, ni que los dos "solucionen", pero eso es un tema aparte.

2025-01-17 13:19 UTC, mmnuria commented
> ¿Te parece que esperemos hasta que ellos lo aprueben? Al fin y al cabo, ellos son los que tienen que decidir si los cambios que han hecho son correctos o no. Por lo pronto, no veo muy correcto que repitas dos veces el mismo mensaje de commit, ni que los dos "solucionen", pero eso es un tema aparte.

de acuerdo profesor, solicito revision @juanmaaf y @hossam1522. Gracias de antemano por vuestro tiempo.

2025-01-17 19:08 UTC, hossam1522 reviewed
Te dejo algunos comentarios. ¡Mucho ánimo!

2025-01-17 19:08 UTC, hossam1522 commented on docs/gestor_tareas.md
> +  La herramienta Snyk Advisor o el propio github se utilizarán para evaluar la cantidad de issues, pull requests y las versiones más recientes de cada herramienta.
Que la herramienta tenga commits o versiones recientes lo compro.

En cambio, no creo que la cantidad de issues y pull requests que tenga una herramienta sean de relevancia. Además de la comunidad, aunque pueda ser indicativo de que algo está mantenido, no tiene por qué ser así realmente; al final del día, los que mantienen son los desarrolladores.

Además, no sé si en snyk advisor aparecen estas herramientas. En caso de encontrarlas (sea en snyk o en cualquier otra página de comparaciones) estaría bien enlazarlo aquí.

2025-01-17 19:08 UTC, hossam1522 commented on docs/gestor_tareas.md
> +- **Comunidad y mantenimiento:** Es un proyecto activo que tiene una comunidad en continuo crecimiento, pero su [último commit](https://github.com/adriancooney/Taskfile/commits/master/) fue hace 8 añ
Patinada, task es https://github.com/go-task/task. Último commit de hace 2 semanas.

2025-01-17 19:08 UTC, hossam1522 commented on docs/gestor_tareas.md
> +A partir de lo expuesto anteriormente, podríamos elegir entre las herramientas **Sage**, **Just** y **Make**. En primer lugar, descartamos **Sage** debido a su falta de madurez. En cuanto a **Make**
No puedes descartar una herramienta por algo que no viene en los criterios. ¿Cómo que falta de madurez?

2025-01-17 19:08 UTC, hossam1522 commented on makefile
> +	rm -rf bin/
¿Y todo esto? Podrías incluir solo lo necesario. Si vas necesitando más ordenes a medida que avanzas en el proyecto, ya se introducirán más tarde, ¿no?

2025-01-18 08:33 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Comunidad y mantenimiento:** Es un proyecto activo que tiene una comunidad en continuo crecimiento, pero su [último commit](https://github.com/adriancooney/Taskfile/commits/master/) fue hace 8 añ
Gracias por la corrección, tenia el github equivocado.

2025-01-18 08:35 UTC, mmnuria commented on makefile
> +	rm -rf bin/
Bueno en principio son las ordenes más basicas en los proyectos segun mi experiencia, es por ello que los añadí para tenerlos ya incorporados. Igualmente, no creo que sea algo tan relevante para superar el objetivo ¿no crees?

2025-01-18 09:15 UTC, JJ commented on makefile
> +	rm -rf bin/
¿De veras crees que te merece la pena discutir esto? ¿Además, a una persona que *ya ha superado la asignatura y que está dedicando su tiempo a ayudarte*?

2025-01-18 11:26 UTC, mmnuria commented on makefile
> +	rm -rf bin/
Tiene razon profesor, disculpa.

2025-01-18 21:39 UTC, mmnuria commented
@hossam1522 tras revisar tus observaciones, me he dado cuenta que realmente no es necesario mencionar Snyk Advisor, ya que, efectivamente no aparecen las herramientas seleccionadas.

Por otro lado, he reducido la cantidad de órdenes a las requeridas para el objetivo ya que, realmente el resto no eran necesarias.

2025-01-18 21:39 UTC, mmnuria commented
@juanmaaf @hossam1522 solicito revision.

2025-01-19 11:59 UTC, hossam1522 commented on docs/gestor_tareas.md
> +  Se considerará el repositorio de código oficial para evaluar la cantidad de commits y las versiones más recientes de cada herramienta. Adicionalmente, se valorará de forma positiva la antigüedad de
Más que cantidad de commits, convendría evaluar si estos son recientes o no...

2025-01-19 11:59 UTC, hossam1522 commented on docs/gestor_tareas.md
> +- **Proyecto en activo y sujeto a mantenimiento continuo:** Aunque la herramienta se considera inactiva, se ha recibido un [último commit](http://git.savannah.gnu.org/cgit/make.git/refs/) hace 6 sema
¿De dónde has sacado que la herramienta se considera inactiva?

2025-01-19 13:36 UTC, mmnuria commented on docs/gestor_tareas.md
> +  Se considerará el repositorio de código oficial para evaluar la cantidad de commits y las versiones más recientes de cada herramienta. Adicionalmente, se valorará de forma positiva la antigüedad de
Eso es verdad, la cantidad de commits que haya no tiene por qué determinar que sea mejor proyecto, no obstante si son recientes o no, indica que la herramienta cuente con un mantenimiento continuo actualmente.

2025-01-19 13:40 UTC, mmnuria commented on docs/gestor_tareas.md
> +- **Proyecto en activo y sujeto a mantenimiento continuo:** Aunque la herramienta se considera inactiva, se ha recibido un [último commit](http://git.savannah.gnu.org/cgit/make.git/refs/) hace 6 sema
Realmente he mezclado inactividad con falta de releases recientes (la última [versión](https://ftp.gnu.org/gnu/make/) es de hace 2 años), dado que es confuso, lo corrijo.

2025-01-19 13:46 UTC, mmnuria commented on docs/gestor_tareas.md
> +  Se considerará el repositorio de código oficial para evaluar la cantidad de commits y las versiones más recientes de cada herramienta. Adicionalmente, se valorará de forma positiva la antigüedad de
No me parece arbritario por que no son excluyentes: es mejor emplear una herramienta que tenga versiones recientes respecto a otra que tiene versiones recientes y además un historial de contribuciones extenso? Creo que la segunda opción es considerablemente más oportuna que la primera. 

Si partimos de la base de que buscamos un gestor de tareas que realmente sea útil para el proyecto y no consideramos la antigüedad, estaríamos dejando la puerta abierta a que herramientas que estén de moda puedan ser consideradas como una opción (por ejemplo un proyecto que lleva existiendo 3 meses y se hace viral entre desarrolladores: que garantías tiene de que no va a ser abandonado en cualquier momento?) arriesgándonos a crear deuda técnica en el proyecto por tener que cambiar la herramienta por otra en algún momento. 

Este argumento sumado al hecho de que menciono que Sage y Just también cumplen, pero Make podría ser realmente mejor opción por su antigüedad, sugieren que no estoy tratando de justificar Make.

Por otro lado si que veo que debo ajustar la elección por que aunque Make cumple por la parte de antigüedad y ha recibido algunos commits últimamente, la última versión fué publicada hace más de un año y eso lo descartaría al igual que sucede con Mage. Esto igualmente no quita que el criterio tiene intención de realizar una buena elección y  no de generar un filtro intencional para que sólo Make lo cumpla por las razones que he mencionado.

2025-01-19 13:47 UTC, mmnuria commented on docs/gestor_tareas.md
> +En primer lugar, descartamos **Mage** ya que no ha recibido actualizaciones en el último año.
Esto es cierto y lo voy a corregir acorde a ser consecuente con el criterio de elección.

2025-01-19 13:55 UTC, mmnuria commented
Os agradezco las revisiones que me habéis dejado y he realizado los ajustes necesarios para mejorar los cambios propuestos. Por tanto, solicito revisión @hossam1522 @juanmaaf

2025-01-19 15:10 UTC, juanmaaf commented on docs/gestor_tareas.md
> +  Se considerará el repositorio de código oficial para evaluar la cantidad de commits y las versiones más recientes de cada herramienta. Adicionalmente, se valorará de forma positiva la antigüedad de
¿Te das cuenta que el primer párrafo que has escrito justifica que el criterio no es objetivo? "¿Es mejor?" "Creo". Y te lo digo desde mi experiencia por ejemplo para seleccionar el gestor de dependencias para un proyecto Python. Elegí UV a pesar de ser una herramienta muy moderna y poco conocida pero que era mejor que otros gestores de dependencias que puse, basándome en comparaciones objetivas que aportaba la propia herramienta.

2025-01-19 15:14 UTC, juanmaaf commented on docs/gestor_tareas.md
> +  Se considerará el repositorio de código oficial para evaluar la cantidad de commits y las versiones más recientes de cada herramienta. Adicionalmente, se valorará de forma positiva la antigüedad de
Por otro lado, te invito a revisar el PR de muchos compañeros en distintos objetivos y verás que es un error explicar aquí qué es lo que has hecho. Responde a los comentarios con cambios si lo consideras y commits. También piensa en la asignatura en la que estamos. ¿De qué deuda técnica hablas en el futuro? Si la herramienta es ampliamente utilizada y aceptada HOY, ¿por qué te preocupas por el futuro? Creo que estás tratando de jutificar un criterio arbitrario pero no deja de serlo. No puedo darte el apto si leo y entiendo algo que no creo que esté bien. Aunque consigas el apto, no te aseguro que con la aplicación de este criterio superes el objetivo.

2025-01-19 22:06 UTC, mmnuria commented
Tras realizar cambios vuelvo a solicitar revisión @juanmaaf @hossam1522

2025-01-20 07:39 UTC, hossam1522 approved these changes
Me parece correcto.

2025-01-20 09:20 UTC, juanmaaf approved these changes
No tengo nada más que añadir. Tienes mi apto.

2025-01-20 11:19 UTC, mmnuria commented
@JJ solicito revision.

2025-01-20 12:33 UTC, JJ approved these changes
:+1: y muchas gracias a @hossam1522 @juanmaaf y @antoniorr02 por el trabajo realizado.

2025-01-20 12:53 UTC, merged