[IV-24-25] Delivery objetive 1
mmnuria/PersonalSportCalendary pull request #6
Opened 2024-09-29 18:08 UTC by mmnuria

Sobre los milestones:

* [✅ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ✅] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ✅] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ✅] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ✅] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ✅] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [✅ ] ¿Los milestones son graduales, o hay un salto grande entre ellos? Graduales.
* [ ✅] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ✅] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [✅ ] ¿El milestone 0 es mínimo *y* viable?
* [✅ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ✅] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

Sobre las historias de usuario:

* [ ✅] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ✅] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ✅] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ✅] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo? El usuario desea hacerlo, ya que tiene que introducir la minima información pero la necesaria para satisfacer sus necesidades.

2024-10-01 08:44 UTC, antoniorr02 commented
Buenas me han asignado para revisar tu repositorio.

Creo que sería altamente recomendable que añadieses tanto los hitos como las HUs a la doccumentación del proyecto y no sólo en los issues de github.

Por otro lado, te recomiendo marcar las casillas con una x en el formulario de comprobación para que github las reconozca como marcadas.

2024-10-01 08:49 UTC, antoniorr02 commented
Buenas me han asignado para revisar tu PR.

En primer lugar, te recomiendo marcar las casillas con una x en el formulario de comprobación para que github las reconozca como marcadas

2024-10-01 08:53 UTC, antoniorr02 commented on docs/config-milestones.md
> +        >
"Entendimiento" no puede considerarse un producto, con lo que no cumple con el PVM.

2024-10-01 08:53 UTC, antoniorr02 commented on docs/config-milestones.md
> +    - [Milestone 3: Inclusión de ejercicios de estiramiento (HU003)](./images/milestone3.png)
En el PVM se busca desarrollar un producto mínimo en el menor tiempo posible, que cumpla unos requisitos mínimos, permitiendo la flexibilidad necesaria para ir añadiendo mejoras incrementales al programa. ¿Te parece correcto incluir hitos tan avanzados desde una etapa tan temprana del proyecto?

2024-10-01 09:00 UTC, mmnuria commented on docs/config-milestones.md
> +    - [Milestone 3: Inclusión de ejercicios de estiramiento (HU003)](./images/milestone3.png)
No comprendo donde se observa que los hitos están avanzados, considero que recorren poco a poco las funciones que debe realizar la aplicación, en primer lugar seleccionando tiempo disponible (hito 1), seguido de selección de material (hito 2) y por ultimo, proponer a todo lo anterior ejercicios de estiramientos (hito 3).

2024-10-01 09:05 UTC, mmnuria commented on docs/config-milestones.md
> +        >
El entendimiento del problema viene reflejado con una serie de entregables para que cumpla con el PVM, como se desarrolla en el milestone 0: "Este hito se centra en comprender las necesidades de los usuarios y establecer un plan inicial para el desarrollo de la aplicación. Se realizará un análisis de las historias de usuario para garantizar que todos los requisitos están claros."

Entregables:

- Documentación sobre las necesidades y problemas de los usuarios.
- Revisión de las historias de usuario y criterios de aceptación.

Criterios de éxito:

Todos los miembros del equipo comprenden las historias de usuario y están alineados con los objetivos del proyecto.

No entiendo entonces, porque no se puede considerar como un PVM.

2024-10-01 17:03 UTC, antoniorr02 commented on docs/config-milestones.md
> +        >
Te invito a revisar las correcciones del profesor en mi PR y podrás ver como he tenido esta discusión ya con él.

2024-10-01 17:05 UTC, antoniorr02 commented on docs/config-milestones.md
> +    - [Milestone 3: Inclusión de ejercicios de estiramiento (HU003)](./images/milestone3.png)
La idea de la metodología PVM no es definir el producto final en su totalidad, si no definir una etapa temprana del desarrollo del mismo. Con ello, abordar funcionalidades auxiliares como ésta no se recomienda en el ámbito de dicha metodología.

2024-10-02 16:10 UTC, juanmaaf reviewed
Buenas, se me ha asignado revisar tu PR. Basándome en la lista de comprobación, en general se ve correcto aunque he realizado una serie de puntualizaciones que creo que te pueden ayudar a tener el apto en el objetivo.

2024-10-02 16:10 UTC, juanmaaf commented on docs/HUs/HUs.md
> +1. [HU001 Como usuario con múltiples responsabilidades, quiero que mis necesidades relacionadas con el ejercicio y la falta de tiempo sean comprendidas y bien documentadas, para poder mantenerme acti
Has incluido en el nombre del issue HU001 todo su contenido. Te recomiendo sustituir el nombre por uno más corto y significativo, como has hecho en el resto de issues.

2024-10-02 16:10 UTC, juanmaaf commented on docs/config-milestones.md
> +    - [Milestone 0: Entendimiento del problema y planificación inicial](./images/milestone0.png)
Igual que indica @antoniorr02, el Milestone 0 no puede denominarse "Entendimiento del problema". Ten en cuenta que el resultado de cada hito es un producto que cumpla con el criterio PVM.

2024-10-02 16:10 UTC, juanmaaf commented on docs/config-milestones.md
> +    - [Milestone 3: Inclusión de ejercicios de estiramiento (HU003)](./images/milestone3.png)
La metodología de desarrollo ágil te hará descubrir poco a poco la solución a tu problema. ¡Aún no la sabes! ¿Consideras correcto incluir tantos hitos en tu proyecto? Ten en cuenta que podrás marcar nuevos objetivos a medida que desarrolles el proyecto.

2024-10-03 07:59 UTC, mmnuria commented on docs/config-milestones.md
> +    - [Milestone 3: Inclusión de ejercicios de estiramiento (HU003)](./images/milestone3.png)
pero, no es una funcionalidad auxiliar, es una funcionalidad necesaria para la resolución completa del problema principal, solamente que, lo he dividido de forma que, primero se realice lo que mayor prioridad tiene el usuario y por ultimo lo que menos, pero no por ello, menos importante o "auxiliar".

2024-10-03 08:01 UTC, mmnuria commented on docs/config-milestones.md
> +    - [Milestone 3: Inclusión de ejercicios de estiramiento (HU003)](./images/milestone3.png)
En principio he ido dividiendo el problema principal del usuario en pequeños hitos (como dijo el profesor en clase) por lo que me ha llevado a la obtención de esa cantidad, igualmente, no creo que sea un problema ya que, son partes necesarias y obligatorias de realizar si quiero conseguir cumplir con las necesidades de los usuarios.

2024-10-03 10:57 UTC, mmnuria commented
@antoniorr02 y @juanmaaf he añadido cambios al PR, ya me decís lo que os parece y si debo de incorporar algo más.

2024-10-03 11:52 UTC, giorgiogiovanni requested changes
Buenas, me han asignado para revisar la PR.

Como @antoniorr02 ya ha comentado cosas acerca del propio objetivo, me centro en otras cuestiones generales...

El repositorio pretende contener el proyecto y la documentación de cómo se ha llegado a ese diseño. En algunos casos puntuales se requiere alguna información extra, como en el objetivo 0 cuando se entrega la correcta configuración de git, pero que se expecifica posteriormente que debe desaparecer del repositorio (a partir del objetivo 1), pues es información que no tiene sentido que esté en un repositorio de código.

Los documentos como `config-issues.md` no tienen sentido. Quizás en un repositorio general de la asignatura con guías _How to_ podría tenerlo, pero no aquí. La idea es crear un documento donde queden expresadas las Historias de usuario simplemente y no una guía donde explicar como convertir estas en Issues de Github.

Es por ello que te recomiendo revisar en general los documentos y crear aquellos que expresen las HU o Milestones y no como una guía tutorial de github (y consecuentemente eliminar las capturas de pantalla relacionadas, que no aportan nada)

2024-10-03 11:52 UTC, giorgiogiovanni commented on README.md
> +Finalmente la [clave publica](./docs/images/ClavePublica.png), el [nombre y correo](./docs/images/NombreyCorreo.png) se puede ver que se ha configurado correctamente en GitHub.
Esta parte ya no es necesario mantenerla en el repositorio

Más info:
https://github.com/JJ/IV/blob/master/documentos/proyecto/1.Planificacion.md#entrega-de-la-pr%C3%A1ctica

2024-10-03 17:10 UTC, mmnuria commented on README.md
> +Finalmente la [clave publica](./docs/images/ClavePublica.png), el [nombre y correo](./docs/images/NombreyCorreo.png) se puede ver que se ha configurado correctamente en GitHub.
Hola! pues en principio, me gustaba la idea de incorporar el paso a paso de como realizar cada uno de los issues, milestones, etc, detalladamente. Esto es porque como el profesor en el objetivo 0 me mencionó que había que explicarlo más, añadir inormación y capturas de las claves, configuración etc, consideré el añadirlo de igual forma en este objetivo para que quedase claro y además, sirviera de guía de apoyo para alguien que no supiera de donde aparece cada una de las partes.

Si no te improta, esta parte si que me gustaría dejarla, al final es un toque personal del que dediqué bastante tiempo.

2024-10-03 17:16 UTC, mmnuria commented on README.md
> +Finalmente la [clave publica](./docs/images/ClavePublica.png), el [nombre y correo](./docs/images/NombreyCorreo.png) se puede ver que se ha configurado correctamente en GitHub.
Por otro lado, ¿porque no se debe mantener la configuración y las claves? en principio no encuentro donde lo indique.

2024-10-04 12:27 UTC, giorgiogiovanni commented on README.md
> +Finalmente la [clave publica](./docs/images/ClavePublica.png), el [nombre y correo](./docs/images/NombreyCorreo.png) se puede ver que se ha configurado correctamente en GitHub.
![image](https://github.com/user-attachments/assets/7dcb9e09-8b3a-4d73-a6db-40fd256e5789)

De todas formas, el profesor suele indicar que se eliminen. No es una buena practica tener cierta información expuesta publicamente.

2024-10-04 12:44 UTC, mmnuria commented on README.md
> +Finalmente la [clave publica](./docs/images/ClavePublica.png), el [nombre y correo](./docs/images/NombreyCorreo.png) se puede ver que se ha configurado correctamente en GitHub.
mmm de acuerdo, ¿crees entonces que los pantallazos de como se crea un issue puede provocarme algun problema de cara al publico? Si es así, pues lo eliminaré...

2024-10-07 11:34 UTC, mmnuria commented on docs/config-milestones.md
> +        >
No comprendo porqué "planificacion inicial" no es algo que pueda mencionar, ya que explico cada uno de los entregables y pasos a seguir para que cumpla con PMV. Agradecería si se puede revisar al completo todos los cambios que he realizado y se me proporcione un feedback un poco mas concreto, para poder hacer ya la entrega.

2024-10-07 11:35 UTC, mmnuria commented
Solicito que se me mencione que partes nuevamente no me aceptan, para hacer la entrega del objetivo. Gracias. @juanmaaf @antoniorr02 @giorgiogiovanni

2024-10-08 07:22 UTC, antoniorr02 commented on docs/config-milestones.md
> +        >
Como ya te dije en los hitos debe de entregarse un producto y una planificación no es ningún tipo de producto al usuario. Como te mencioné esto es algo que discutí largo y tendido con el profesor en mi pull request. Nuevamente te sugiero que revises dicha conversación ya que se habla concretamente de las mismas propuestas que has hecho y estás haciendo para el hito 0.

2024-10-08 07:42 UTC, mmnuria commented
@antoniorr02 he modificado lo que me has sugerido del milestone 0, quedo a la espera de tu respuesta.

2024-10-08 08:08 UTC, antoniorr02 approved these changes
Si bien el nombre del hito 0 es correcto, no me queda muy  claro si la explicación de dicho hito será suficiente de cara a que el compañero que se te asigne pueda completarlo de forma satisfactoria.

En cualquier caso, te doy mi aprobación para que en última instancia @JJ aporte sus correcciones y pueda validarte el objetivo.

2024-10-08 10:56 UTC, juanmaaf approved these changes

2024-10-09 10:26 UTC, mmnuria commented
@JJ solicito corrección por su parte, dos compañeros me han aceptado el PR. Gracias!

2024-10-09 15:37 UTC, JJ commented on docs/HUs/HUs.md
> +1. [**HU001:** Gestión de ejercicio para personas con falta de tiempo:](./HU001.png)
"Gestión" es una posible solución al problema, no un problema. El título y el contenido de una HU deben reflejar un problema, no una solución. Como dice [el guión](https://jj.github.io/IV/documentos/proyecto/1.Infraestructura):

> Las historias de usuario siempre expresan deseos y beneficios, están relacionadas con la lógica de negocio y están en el dominio del problema.

2024-10-09 15:39 UTC, JJ commented on docs/HUs/HUs.md
> +    >Como usuario con una vida ocupada, quiero asegurarme de que se entienden bien mis limitaciones de tiempo y las dificultades que enfrento para mantenerme físicamente activo. Esto me permitirá rec
¿Crees que con esto alguna persona que lea la HU puede ponerse a trabajar en la modelización de un problema? ¿Qué problema expresan en concreto? ¿Las limitaciones de tiempo? ¿La vida personal, laboral y bienestar físico? ¿Cómo se pueden modelizar estas cosas?

2024-10-10 07:03 UTC, mmnuria commented
@JJ ya he realizado los cambios que me ha mencionado, creo que ahora se entiende mejor todo. Gracias! Espero feedback

2024-10-10 07:08 UTC, JJ reviewed
Por favor
1. Resuelve los comentarios
2. Haz un rebase de la rama principal para que no aparezcan los ficheros que no corresponden a este objetivo.

2024-10-10 07:08 UTC, JJ commented on docs/config-repo.md
Esto debería estar en la rama principal, no aquí.

2024-10-10 07:43 UTC, mmnuria commented
@JJ ya he resuelto los comentarios, he realizado rebase y no aparecen los archivos incorrectos.

2024-10-10 09:35 UTC, JJ requested changes
Ha mejorado algo el contexto, pero sigues introduciendo términos que no tiene por qué entender otra persona. La HU es para que la entienda cualquiera y se ponga a crear issues y eventualmente programarlos, no para ti.

2024-10-10 09:35 UTC, JJ commented on docs/HUs.md
> +    >   - Realizar rutinas de ejercicio cortas y flexibles (de 5 a 30 minutos), según mi disponibilidad.
"Rutina de ejercicios" tampoco es un término que tenga una acepción unívoca. Una ve más, deberías especificar en un user journey o de alguna otra manera qué es una rutina de ejercicio.

Ten en cuenta que si las rutinas de ejercicios no están en un formato estructurado adecuado, extraerlas del documento puede ser también un problema en sí (pero sería *otro* problema y por tanto otra historia de usuario)

2024-10-10 19:11 UTC, mmnuria commented
@JJ creo que ahora se puede entender mejor, sin necesidad de añadir un user journey. Gracias de nuevo.

2024-10-11 05:26 UTC, JJ requested changes
Y vuelvo a insistir, ¿has considerado que extraer los ejercicios de un texto semi estructurado puede ser también un problema?

2024-10-11 05:26 UTC, JJ commented on docs/HUs.md
> +    >   - Realizar un conjunto de ejercicios cortos y flexibles (de 5 a 30 minutos), según mi disponibilidad.
Has cambiado rutina por conjunto. ¿De veras que crees que eso ha aclarado algo?

2024-10-12 12:58 UTC, mmnuria commented
@JJ he añadido un user journey para que se pueda entender mejor a lo que se refieres "rutina de ejercicios", especificando cada uno de lo que necesita incluir.

2024-10-14 05:32 UTC, JJ commented
> @JJ he añadido un user journey para que se pueda entender mejor a lo que se refieres "rutina de ejercicios", especificando cada uno de lo que necesita incluir.
> 
> Por otro lado, en principio quiero generar rutinas sin imagenes, solamente texto explicativo, pero adicionalmente, quiero adentrarme en el reto de añadir links, que accedan a videos de youtube (por ejemplo) con la explicacion de esos ejercicios. Esos links puedo generarlos de manera dinamica, haciendo uso del nombre del ejercicio, por ejemplo si en la base de datos se llama "sentadilla sin peso" generar un link estilo: https://www.youtube.com/results?search_query=sentadillasinpeso , si el siguiente ejercicio es "flexiones de pecho" será https://www.youtube.com/results?search_query=flexionesdepecho , etc.

Eso no requiere ninguna lógica de negocio y por tanto no tiene mayor relevancia para la asignatura. Por otro lado, en cualquier momento decir lo que tú quieres no entra en el proceso de desarrollo, porque lo que hay que buscar es lo que la persona para la que estás desarrollando, la clienta, quiere. Y es imposible saber si quiere enlaces a Youtube, a Tiktok, o a nada.
> 
> De esta manera se generarán links hacia esos ejercicios explicados en youtube sin necesidad de almacenarlos en una base de datos.

¿Crees que eso tiene que ver algo con el milestone actual?

2024-10-14 06:06 UTC, JJ requested changes
El problema principal es que de la primera HU no queda claro que haya realmente un problema más allá del trivial "añadir ejercicios hasta que sobre pasen la duración disponible". No parece que haya que aplicar ningún algoritmo a los ejercicios para que sigan una secuencia determinada, o para que maximicen alguna cualidad restringidas por una duración. En el "user journey" que has añadido (que no es tal, porque estás haciendo referencias a "bases de datos" y otros elementos que no forman parte del vocabulario del usuario) no aclaras de qué se trata esa cualidad.

Por otro lado, tienes diferentes problemas de detalle, y sobre todo el problema principal es que no contestas realmente a las objeciones que se te hacen. Repetidamente he comentado la posibilidad de que extraer los ejercicios de una fuente poco estructurada sea un problema a resolver previamente, y lo has rechazado. Has cambiado contenido simplemente por eliminar el comentario, o has resuelto comentarios simplemente contradiciendo a la persona que los hace. Lo que te he comentado de los milestones te lo comentó alguien [aquí](Los criterios de viabilidad tienen que ser, si no totalmente objetivos, al menos que sigan algún criterio más o menos objetivo. "Que lo apruebe alguien" no es objetivo. ¿Qué pasa si no lo aprueba? ¿Está mal entonces? Si no se puede comprobar de forma totalmente objetiva, habrá al menos que indicar algún criterio cualitativo o cuantitativo que se vaya a seguir a la hora de aprobarlo o no.)

En este commit 1b26582e8d0876cb0c8f1594c1c103ac4e762127, para eliminar un comentario, has añadido una frase "Aquí te dejo...", cambiado "Como usuario por una vida ocupada..." por "Soy una persona adulta con una carga de trabajo alta..." sin realmente contestar al [comentario que te hice](https://github.com/mmnuria/PersonalSportCalendary/pull/6#discussion_r1794910722) 

Te he insistido repetidamente en que aclares qué son esas soluciones. No porque a mi me apetezca ni tenga esa manía, sino porque sin ningún tipo de aclaración no se pueden hallar esos "elementos claves" que pones en tu milestone 0 ni el "modelo del problema" (aparentemente algo diferente) que hay que entregar ahí; y no solo por eso, sino porque si no se aclara no se pude saber si hay una lógica de negocio sustancial.

Te agradecería que tuvieras en cuenta que el proceso de revisión de un PR no es simplemente un trámite que hay que pasar, y resolver los comentarios es algo que hay que hacer para pasar el objetivo. La revisión de PRs es un proceso de transmisión de conocimiento entre el equipo, en la empresa y también pretendo que lo sea aquí. Es parte del proceso de mejora continua por el que aboga el desarrollo ágil. Es para asegurar la calidad del resultado, y seguir el proceso es precisamente lo que asegura esa calidad, no simplemente resolver los comentarios. Te agradecería que, para optimizar tu tiempo, el de tus compañeros y el mío, te lo tomaras así.

2024-10-16 05:56 UTC, JJ requested changes
Por favor, trata de entender qué es un milestone, para qué sirve y como se usa. Si no entiendes qué es y qué función ocupa, es muy difícil que lo describas correctamente. Y si no lo describes correctamente, es imposible que lo uses, ni correctamente ni incorrectamente. Y en esta asignatura lo que se describe se va a usar.

Te aconsejo también que leas los párrafos que siguen a ese en el fichero enlazado.

2024-10-16 05:56 UTC, JJ commented on docs/config-milestones.md
> +**Objetivo:** Realizar un análisis exhaustivo del problema, definiendo las necesidades clave del dominio y estableciendo las metodologías para modelar la solución.
Nuria, sé que no me has pedido revisión, pero te rogaría que no fueras por aquí. Mira [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md):

> Para empezar, el [error frecuente del objetivo 0 mencionado en la introducción](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md) se sigue produciendo. En este caso, cosas como: 
- **Poner el "objetivo" de un milestone.**

2024-10-16 09:50 UTC, mmnuria commented
Han vuelto a aparecer algunos archivos que aparecen como editados los cuales ya había solucionado la semana anterior en clase. He vuelto a realizar un rebase y nada... siguen apareciendo, no comprendo que puedo hacer nuevamente para este problema. Entiendo que cuando tenga aprobado este PR y haga merge a la rama main, se solucionará todo esto...

2024-10-16 16:39 UTC, JJ requested changes
Te aconsejo que leas detenidamente [el tercer párrafo de la introducción a los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md). Si no entiendes la necesidad de hacer unas historias de usuario correctas técnicamente y unos milestones que guíen el desarrollo, ni para qué sirven, ni como se usan, podemos hacer una ronda infinita de revisiones, pero no nos van a acercar a ninguna solución, porque el problema no es que no entiendas el concepto, sino simplemente que entender el concepto o no parece ser algo irrelevante frente a la necesidad de "pasar este objetivo"
Mañana en clase, o pasado, puedes hacerme las preguntas y dudas que tengas sobre estos conceptos y por qué es necesario entenderlos para poder continuar no ya con la asignatura (que tiene la importancia que tiene, o ninguna) sino comprender cómo funciona el desarrollo en cualquier empresa hoy en día.

2024-10-16 16:39 UTC, JJ commented on README.md
> +> Puedes encontrar más información en el archivo [noticias](./docs/news.md) sobre las diferentes consecuencias y riesgos para la salud que conlleva el no realizar suficiente actividad fisica.
Si esto no es relevante para el desarrollo, es mejor que no lo incluyas.

2024-10-16 16:39 UTC, JJ commented on README.md
> +Finalmente la [clave publica](./docs/images/ClavePublica.png), el [nombre y correo](./docs/images/NombreyCorreo.png) se puede ver que se ha configurado correctamente en GitHub.
¿De qué forma está esto resuelto?

2024-10-16 16:39 UTC, JJ commented on docs/HUs.md
> +Soy un adulto con una alta carga de trabajo y responsabilidades familiares. Mi salud se está viendo afectada porque no tengo suficiente tiempo para dedicar al ejercicio. Necesito encontrar una manera
¿Crees que a partir de esta HU puede alguien modelizar un problema?
El problema que enuncia es ambiguo. ¿Es un problema no tener suficiente tiempo? ¿Mantenerse físicamente activo?
Una HU es un documento de trabajo para comenzar a desarrollar. ¿Crees que hay suficiente en esta HU para que alguien se ponga a trabajar modelizando el problema?

Esto es algo que ya te dije [aquí](https://github.com/mmnuria/PersonalSportCalendary/pull/6#discussion_r1793751906) y [aquí](https://github.com/mmnuria/PersonalSportCalendary/pull/6#pullrequestreview-2365334445). Cambiar el texto para "resolver" el comentario sin realmente hacer ninguna mejora no conduce más que a más trabajo por mi parte y por la tuya, sin acercarte a conseguir el objetivo.

2024-10-16 16:39 UTC, JJ commented on docs/HUs.md
> +Tengo dificultades para organizar mi tiempo y planificar cuándo puedo hacer ejercicio. Con mi agenda ocupada, es complicado saber el tiempo necesario para realizar cada ejercicio de manera que sea su
¿En qué se diferencia esto de la primera? ¿De qué forma describe un problema?

2024-10-16 16:39 UTC, JJ commented on docs/NombreyCorreo.png
Esto hay que borrarlo antes de hacer el PR. Os ruego que el PR incluya solo lo necesario para revisar el objetivo.

2024-10-16 16:39 UTC, JJ commented on docs/config-milestones.md
> +Crear un **modelo claro y funcional del problema** que incluya los elementos clave necesarios para la generación dinámica de rutinas de ejercicio. Este modelo debe permitir la personalización de ruti
Creo que ya te lo he enlazado alguna vez, pero quizás haga falta recordarlo. De [los errores comunes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md):

> Aunque los milestones en principio no tienen por qué tener información sobre las historias de usuario, si hay varias historias de usuario hablar de "modelo del problema" o de "lógica de negocio" no es suficiente, porque las dos historias de usuario (o las 5) pueden tener diferentes aspectos del problema,

2024-10-16 16:39 UTC, JJ commented on docs/config-milestones.md
> +Un **documento técnico** acompañado de código que defina:
Creo recordar que ya lo pusiste alguna vez y te indicaron el error. Por esa razón y porque más gente ha hecho lo mismo, está incluido en el fichero de errores frecuentes:

> 

Por favor, no inventéis y pidáis cosas que no vienen a cuento ni sirven realmente para nada. Estoy pensando en pedir "documentos" con el modelo del problema, pero no descarto que metáis diagramas UML o alguna otra cosa igualmente inútil. Un producto es código funcionando, y que siga algún criterio de viabilidad. Punto.

Llegado a este punto, no sigo revisando.

2024-10-17 07:40 UTC, JJ commented on README.md
> +> Puedes encontrar más información en el archivo [noticias](./docs/news.md) sobre las diferentes consecuencias y riesgos para la salud que conlleva el no realizar suficiente actividad fisica.
Modifícalo en la rama `main` y haz un rebase entonces.

2024-10-17 08:02 UTC, mmnuria commented on docs/NombreyCorreo.png
Ya realicé hace semanas el rebase en clase con usted y continúa apareciendo...

2024-10-17 08:07 UTC, JJ commented on docs/config-milestones.md
> +Crear un **modelo claro y funcional del problema** que incluya los elementos clave necesarios para la generación dinámica de rutinas de ejercicio. Este modelo debe permitir la personalización de ruti
¿Es eso lo que has entendido de lo que acabo de decir? ¿Has leído el comentario completo?

2024-10-17 08:09 UTC, mmnuria commented on docs/config-milestones.md
> +Un **documento técnico** acompañado de código que defina:
Considera mejor añadir algo como:

"El modelo será validado mediante pruebas que simulen diferentes situaciones de usuario, asegurando que las rutinas propuestas se ajustan a la disponibilidad de tiempo y cantidad de días de la semana a realizar la rutina descrito por el usuario."

Es lo que tengo pensado para el milestone 0, y para el resto algo parecido, tipo, que la validación sea la propia prueba de la aplicación y de que funcione ajustándose en este caso a la disponibilidad de tiempo y días de la semana del usuario.

2024-10-17 08:22 UTC, mmnuria commented on docs/config-milestones.md
> +Crear un **modelo claro y funcional del problema** que incluya los elementos clave necesarios para la generación dinámica de rutinas de ejercicio. Este modelo debe permitir la personalización de ruti
mmm si profesor, me he leido como 4 veces el archivo de los errores comunes y le prometo que trato de ajustarme a ellos y entenderlos. Le dejo un ejemplo de Milestone 0, para que antes de subir otro cambio al PR, pueda decirme si está mejor o no, segun todo lo que me ha dicho:


### [M0] Modelo del Problema

+ **Descripción**: Realizar un análisis exhaustivo de la HU001 para identificar y definir los elementos clave relacionados con la falta de tiempo para el ejercicio y la dificultad de planificación de éstos. Se debe establecer una metodología que permita modelar y representar las preferencias de los usuarios, los momentos disponibles para entrenar y cómo se relacionan con la creación de rutinas personalizadas. El objetivo es crear un modelo que represente de manera precisa el contexto y las necesidades de usuarios con limitaciones en el tiempo y cantidad de días que disponen para mantener un nivel adecuado de actividad física.

+ **Producto mínimamente viable**: Código que encapsule los elementos fundamentales del dominio (componentes clave que definen como funciona realmente el problema como por ejemplo definiendo "Usuario" con atributos de tiempo disponible, preferencias de intensidad...) y generando una estructura básica para rutinas de ejercicios (colección de ejercicios que se ajustan al tiempo y días que dispone a la semana el usuario para realizar la rutina).

+ **Requisitos para la Validación**:
  - El diseño debe seguir buenas prácticas de modelado, permitiendo que en futuras iteraciones se puedan añadir nuevas variables como materiales disponibles y estiramientos.
  - El modelo será validado mediante pruebas que simulen diferentes situaciones de usuario, asegurando que las rutinas propuestas se ajustan a la disponibilidad de tiempo y cantidad de días de la semana a realizar la rutina descrito por el usuario.
  
  He de añadir que he modificado las Hus para que se ajusten tambien a todo lo que me ha mencionado.

2024-10-17 09:15 UTC, mmnuria commented
@JJ he realizado el rebase y demás para que no aparezcan los cambios que realicé en el objetivo 0, hay uno del README.md que se me resiste por algún motivo. El resto los he arreglado.

He modificado los archivos de las Hus y milestones completos, ya que, no estaban bien. Me he ceñido a las explicaciones que me has otorgado, además de simplificar  las HUs, ya que, había 2 que se parecían mucho. Espero poder haberme acercado algo más. Gracias por su tiempo.

2024-10-17 10:10 UTC, JJ commented on docs/config-milestones.md
> +Crear un **modelo claro y funcional del problema** que incluya los elementos clave necesarios para la generación dinámica de rutinas de ejercicio. Este modelo debe permitir la personalización de ruti
El PR no se comenta en los comentarios, se comenta en el código. Si crees que eso corresponde a lo dicho, envíalo.

2024-10-17 10:19 UTC, JJ requested changes
Me temo que si se siguen sin resolver los problemas indicados repetidamente, no se puede avanzar hacia la consecución del objetivo. No sé muy bien como decirlo ya, porque hago el comentario, se modifica la línea correspondiente para que desaparezca sin resolver el problema, y tengo que volver a hacer el comentario otra vez.

Por resumir un poco
1. Hay que aclarar todos los aspectos del problema del que estamos tratando para que se pueda trabajar en él, entre otras cosas para ver si *realmente* es un problema que se pueda tratar en la asignatura
2. Se deben evitar "patrones frecuentemente repetidos". Si alguna cosa no se entiende, no se pone, y el profesor tratará de guiar al estudiante y dar recursos para que lo entienda.
3. Entender y responder a los comentarios de los revisores es imprescindible para poder avanzar en el desarrollo de un producto, en esta asignatura y en cualquier trabajo de desarrollo.

2024-10-17 10:19 UTC, JJ commented on docs/HUs.md
> +Soy Ana, una gerente de proyectos en una empresa de tecnología y madre de dos niños pequeños. Mi día está lleno de reuniones, entregas de proyectos y responsabilidades familiares, como ayudar a mis h
De veras que no sé ya como decirte que *no hay un problema claro definido en esta HUs*. Si 
- No enlazas el User Journey donde explicas qué es "el ejercicio"
- No explicas claramente cuál es el problema más allá de "tengo cinco minutos, voy a buscar una rutina de ejercicios de cinco minutos en Youtube"
- No entiendes que si se trata de lo anterior, *no se puede trabajar con esto en la asignatura*

No sé ya como decírtelo. Pido ayuda a @antoniorr02 @giorgiogiovanni  y @juanmaaf a ver si se lo pueden explicar un poco mejor y/o hacer otro tipo de recomendaciones, porque ya he repetido varias veces que
1. Extraer los ejercicios de un repositorio poco estructurado puede ser un problema a tratar
2. Tratar de optimizar un conjunto de ejercicios con una serie de restricciones puede ser también un problema.

Para 1 y para 2 hay que aclarar el contexto. ¿Dónde están los ejercicios que se van a hacer? ¿Se quiere maximizar el empleo de algún músculo para un tiempo determinado? ¿Cada ejercicio está caracterizado por qué en concreto? ¿Músculos, intensidad, duración, número de repeticiones? En resumen ¿*hay algún problema aquí que se pueda tratar en la asignatura*?

2024-10-21 10:15 UTC, mmnuria commented on docs/HUs.md
> +Soy Ana, una gerente de proyectos en una empresa de tecnología y madre de dos niños pequeños. Mi día está lleno de reuniones, entregas de proyectos y responsabilidades familiares, como ayudar a mis h
El problema que intento tratar se ha desarrollado en los documentos del proyecto, pero, básicamente es: Obtener una aplicación que ayude a las personas ocupadas que no saben como empezar a realizar ejercicios físicos, para ayudarles a que mejoren su flexibilidad, resistencia y energía (para mantener una buena salud). Esto se realizará a través de unas rutinas personalizadas para los usuarios que especificarán el tiempo del que disponen (en minutos), cantidad días de la semana para hacer ejercicio, materiales que posee en casa y la intensidad de la rutina con la que quiere la rutina (del 1 al 10). 

La diferencia fundamental con "tengo cinco minutos, voy a buscar una rutina de ejercicios de cinco minutos en Youtube", radica en que la aplicación pretende maximizar los beneficios obtenidos para cada ejercicio a realizar, adaptándose al usuario mediante la duración, repeticiones y series de cada ejercicios, ademas de los materiales deportivos (si posee) que disponga, el tipo de intensidad y sobre todo, el tiempo que dispone. **Con el objetivo de maximizar el aumento de flexibilidad, resistencia y energía de cada usuario para que aumente una buena calidad de vida y salud.**

En definitiva, la lógica de negocio que sigue esta aplicación trata en qué ejercicios son más adecuados para el usuario en base a su perfil, sus preferencias y las restricciones. Esto es una tarea compleja que involucra criterios como el tipo de ejercicio, la intensidad, la duración, y el equipo disponible.

Con respecto a los datos a utilizar, estoy generando una base de datos estructurada con una serie de tablas relacionadas (rutina, ejercicios y preferencias de usuario) en las que se almacenará diferente información para despues obtenerlas en la generacion de la rutina. Usaré un CSV y lo importaré a la base de datos (en principio MYSQL o PostgreSQL).

2024-10-21 12:44 UTC, JJ commented on docs/HUs.md
> +Soy Ana, una gerente de proyectos en una empresa de tecnología y madre de dos niños pequeños. Mi día está lleno de reuniones, entregas de proyectos y responsabilidades familiares, como ayudar a mis h
> Con respecto a los datos a utilizar, estoy generando una base de datos estructurada con una serie de tablas relacionadas (rutina, ejercicios y preferencias de usuario) en las que se almacenará diferente información para despues obtenerlas en la generacion de la rutina. Usaré un CSV y lo importaré a la base de datos (en principio MYSQL o PostgreSQL).

Os he mencionado repetidamente
1. Que el usuario no tiene que introducir ninguna información
2. Que tenéis que usar sólo código propio. Si para las rutinas en el milestone 1 ya necesitas una base de datos, no estás cumpliendo esto
3. Que consideres la extracción de esas rutinas de alguna fuente no estructurada parte del problema, y de hecho la primera parte.

Es muy complicado progresar hacia la consecución del objetivo si no tienes en consideración ninguno de los comentarios y te lanzas en direcciones que no tienen nada que ver con el desarrollo de la asignatura. Y déjame insistirte también en que estás hablando de "la aplicación" cuando todavía ni siquiera hemos definidido el problema en sus historias de usuario correspondientes. Trabajar desde "la aplicación" hacia atrás no solo es imposible, es que también es incorrecto. Te rogaría que intentaras entender qué es lo que se busca en este objetivo y trataras de ver cómo se puede avanzar en el mismo para poder crear una serie de documentos que ayuden a la persona que desarrolle en el objetivo 2 a trabajar.

2024-10-25 11:18 UTC, mmnuria commented
@JJ tras la conversación que tuvimos el jueves en la clase de practicas, he añadido la problemática de encontrar una base de datos estructurada para el problema, ya me dice si lo ve mejor, espero haberme acercado algo más al objetivo. Gracias.

2024-10-25 12:03 UTC, JJ requested changes
La cuestión siempre es la misma: ¿crees que la HU1 refleja un problema de una clienta, y si lo hace, crees que alguien se podría poner a resolverlo?

2024-10-25 12:03 UTC, JJ commented on README.md
> +Finalmente la [clave publica](./docs/images/ClavePublica.png), el [nombre y correo](./docs/images/NombreyCorreo.png) se puede ver que se ha configurado correctamente en GitHub.
Esto sigue sin resolver, Nuria. Debes aprender a no introducir en los PRs cambios innecesarios. O lo dejas exactamente igual o lo cambias así en main y haces un rebase

2024-10-25 12:03 UTC, JJ commented on docs/HUs.md
> +Como desarrollador de la empresa me encuentro con el problema de que no dispongo de ninguna base de datos estructurada con la que poder comenzar.
Las HUs son siempre desde el punto de vista del cliente, no del desarrollador. Tienes que resolver el problema de la clienta, y expresarlo de forma que la desarrolladora pueda tomarlo y poder proporcionar soluciones. ¿No te parece que mencionando la base de datos estructurada ya estás proponiendo una solución?
Lo que hablamos en clase, si no recuerdo mal, es que Ana había encontrado varias páginas donde describían rutinas, o ejercicios, pero tenía que ponerse a mirar cada una de ellas para poder elaborar una rutina y perdía mucho tiempo. Ana también sabía la dirección de esas páginas, ¿no?

2024-10-26 11:56 UTC, mmnuria commented
@JJ HU001 modificada de acuerdo con lo que hablamos en la clase de prácticas.

2024-10-28 06:35 UTC, JJ requested changes
Por favor, tratad de ajustar lo que escribís a lo que se supone que se tiene que hacer en cada paso del desarrollo del problema, es decir, en cada milestone. Una vez más, describir tareas de la aplicación que tienes en mente y adaptarlas a este marco de desarrollo no es algo que conduzca a una resolución con éxito de este objetivo.

2024-10-28 06:35 UTC, JJ commented on docs/config-milestones.md
> ++ **Descripción:** Para poder comenzar con la resolución del problema (HU001), es necesario contar con una base estructurada de datos con la que apoyarte para la extracción de los ejercicios específi
Una "base estructurada de datos" ¿es un modelo específico del problema? ¿O es algo que necesita el modelo del problema?

2024-10-28 10:04 UTC, mmnuria commented on docs/config-milestones.md
> ++ **Descripción:** Para poder comenzar con la resolución del problema (HU001), es necesario contar con una base estructurada de datos con la que apoyarte para la extracción de los ejercicios específi
algo que se necesita del modelo del problema

2024-10-28 10:06 UTC, JJ commented on docs/config-milestones.md
> ++ **Descripción:** Para poder comenzar con la resolución del problema (HU001), es necesario contar con una base estructurada de datos con la que apoyarte para la extracción de los ejercicios específi
¿Cómo sabes lo que necesita el modelo del problema? ¿No se supone que el milestone es para eso?

2024-10-28 10:26 UTC, mmnuria commented
@JJ creo que ahora se entiende mejor el milestone para el modelo del problema que se necesita resolver

2024-10-29 12:29 UTC, JJ commented
> @JJ creo que ahora se entiende mejor el milestone para el modelo del problema que se necesita resolver

Creo que no nos estamos entendiendo. No se trata de que *yo* lo entienda mejor, o que *se entienda mejor* en abstracto. Se trata de que *tú* entiendas qué es lo que se trata y lo expliques de forma que *sea usable por ti u otra persona*.

2024-10-29 12:44 UTC, JJ reviewed
No voy a comentar el resto, pero realmente tras dar el paso adelante de incluir una historia de usuario que sea más asequible y permita trabajar con el problema (historia que realmente no he revisado tras la última vez, y que quizás tendrías que revisar a la luz de lo visto) estamos dando pasos atrás o simlemente pasos en valde porque no hay ningún avance en tu comprensión de los conceptos fundamentales de este objetivo, que son necesarios para avanzar para el siguiente, simplemente porque los vas a poner en práctica.
La ingeniería de software es mucho pensar y poco escribir (código o cualquier otra cosa). Te aconsejaría que hicieras lo siguiente, para ti misma
1. Escribe en un documento qué entiendes tú, con tus propias palabras, por un producto mínimamente viable.
2. Escribe a continuación cuál te parece que debe ser el primer paso en el desarrollo, el primer producto minimamente viable.

A continuación lee lo que he escrito como comentario y revisa tu definición de los mismos. ¿Estabas equivocada? ¿Tenías razón? ¿En qué partes tenías o no razón? Cuando lo hayas hecho con los comentarios (primero los últimos, pero más atrás también) pasa a los errores frecuentes. ¿Hace falta una vez más revisar esa definición interna para ti? 
Si en esa definición hay palabras que no entiendes, consulta una vez más el guión o simplemetne pregunta en el grupo de Telegram o personalmente a mi, por Telegram o en clase. Finalmente, llegarás a una definición donde comprendas todas las palabras, y puedas expresarlo aplicado a tu caso específico. En ese momento, escríbelo y solicita revisión, por favor. Mucha suerte.

2024-10-29 12:44 UTC, JJ commented on docs/config-milestones.md
> ++ **Descripción:** Este milestone se centra en obtener y organizar la información relevante sobre ejercicios y [rutinas](./rutina-ejercicios.md) de manera que permita crear una base de datos inicial
TL;DR: No, no se trata de eso ni de nada que se le parezca.

## Respuesta más larga

Todas las metodologías de desarrollo están encaminadas a que una persona, autónomamente, sea capaz, encuadrada en un equipo de trabajo, de responder a dos preguntas: 
1. Qué hago ahora
2. Lo que hago está bien.

Consulta, por favor, [la introducción al guión de este objetivo](https://jj.github.io/IV/documentos/proyecto/1.Infraestructura#introducci%C3%B3n).

No hay ninguna parte de esas dos preguntas que una persona pueda responder si le dices lo que tiene que hacer, en este caso, "obtener y organizar la información relevante sobre ejercicios y rutinas".  ¿Cómo sabe lo que tiene que hacer? "Obtener y organizar la información" es un objetivo complejo que implicar resolver una serie de problemas. Pero lo peor no es eso, sino *que no sabe si lo que hace está bien*. ¿Cómo sabe si está bien? No lo sabe: "la información relevante sobre ejercicios" sólo se puede sustanciar, saber si es relevante, si *tú* le dices "Ah, pues sí, esto es relevante. Todo esto de aquí no: no sirve para nada lo que has hecho"
Lo peor no es eso. Imagínate que en una empresa lo único que hay es gente que decide qué tiene que hacer otra gente, y gente que hace lo que le dicen. ¿Te parece que en vez de contratar la empresa a dos personas, una que diga lo que tiene que hacer *y lo haga*? (porque en realidad, el trabajo complicado es *saber qué hay que hacer*, no *hacerlo*

## Pero vamos más allá

Dices que "es fundamental para tener una estructura de datos clara". ¿Estamos extrayendo la información *antes* de saber dónde vamos a meterla?

## ¿Y la base de datos?

Repetidamente os he indicado que este milestone inicial lo va a tomar otra persona para empezar a trabajar en tu proyecto, resolviendo el problema de tu cliente. Esa persona se encuentra con una "base de datos" ¿Qué base datos? ¿En qué milestone se ha hecho esa base de datos? ¿O se ha decidido usar una base de datos y no ninguna base de datos o MongoDB o qué? ¿No se trataba de empezar a trabajar?

## Conclusiones

Hasta que no entiendas que estos son documentos de trabajo y no "prácticas" o "ejercicios de clase" y que *realmente* lo que escribas tiene que ser un documento para empezar a trabajar, no vas a empezar a entender

* Qué es un producto mínimamente viable.
* Qué producto mínimamente viable es, de forma natural, el primero y por qué lo estamos pidiendo (para el objetivo 2)
* Cómo hay que empaquetar y describir ese paquete para que se pueda desarrollar de forma eficiente en un entorno ágil.

2024-11-01 11:47 UTC, mmnuria commented
@JJ He seguido paso a paso todas sus sugerencias, revisando atentamente el objetivo y visualizando nuevamente su video sobre el concepto de "producto mínimamente viable". Esto me ha ayudado a comprender mucho mejor el enfoque que debo darle al proyecto.

Basándome en los ejemplos que comparte en el video, los he adaptado a la problemática de mi proyecto. Además, he aplicado la metodología ágil reduciendo los milestones previstos inicialmente a solo dos, los cuales representan productos mínimamente viables con claridad.

2024-11-04 10:04 UTC, mmnuria commented on docs/config-milestones.md
> ++ **Descripción:** **Módulo que defina la estructura de datos** que va almacenar los ejercicios para la obtención de rutinas y la interfaz del mismo, sin implementación.
He querido ser concisa y clara con la descripción del milestone, ya que, según nos recomendaba, lo más preciso y sin andar en rodeos es mejor, por lo que, todo el mundo debe de saber que es un módulo por ello no lo he definido en la descripción del problema. Básicamente un modulo de la estructura de datos del problema es:

1. Módulo: Una sección de diseño dedicada a un tema o función específica, en este caso, los ejercicios para obtener las rutinas especificas.

2. Estructura de datos: Significa decidir y organizar cómo se va a almacenar cada dato de un ejercicio (nombre, duración, materiales, etc.), es decir, crear el formato y reglas para organizar esta información.

3. Sin implementación: Sólo es necesario diseñar esta estructura, sin escribir el código que guardará o usará esos datos aún.

Es como hacer un esquema o plan detallado de cómo se verá y funcionará la parte de datos de los diferentes ejercicios, sin ponerlo en práctica por ahora.

No considero que se deba de mencionar estos conceptos en un milestone, ya que éste debe de recoger únicamente los aspectos necesarios a realizar, siendo el concepto de "módulo" y "estructura de datos" conceptos muy comunes que todo desarrollador debe comprender, aunque, si prefiere que lo desarrolle para evitar confusiones, así será.

2024-11-04 10:12 UTC, mmnuria commented on docs/config-milestones.md
> ++ **Hus asociadas** HU001.
Soy consciente de que en el fichero de errores frecuentes explica que no se debe mencionar las Hus asociadas pero, la verdad es que me siento confundida porque en el archivo de referencia para la explicación del [objetivo 1](https://jj.github.io/IV/documentos/proyecto/1.Planificacion) menciona literalmente "Alguna **HUs tendrá que asignarse al siguiente milestone, aunque se podrán ir moviendo durante el avance del proyecto; de esta forma se prioriza una HU frente a las otras para comenzar a desarrollar**", ademas de, " Hay que desarrollar la idea en una serie de user journeys; estos en una serie de perfiles de usuario o personas, y a continuación crear una serie de historias de usuario (HU). Se crearán también los hitos (milestones) iniciales en el desarrollo, y **habrá que asignar alguna HU al milestone 0 para poder comenzar a trabajar en el objetivo siguiente.**" y en la lista de comprobación del objetivo 1, uno de ellos dice textualmente "**¿El milestone 0 tiene asignada alguna historia de usuario?**" 

Por todo ello, he dejado mencionada la HUs asociada que tiene cada milestone, ya que desde el principio ha sido lo que se ha ido repitiendo...

2024-11-04 10:35 UTC, mmnuria commented on docs/config-milestones.md
> ++ **Descripción:** **Módulo que defina la estructura de datos** que va almacenar los ejercicios para la obtención de rutinas y la interfaz del mismo, sin implementación.
Por otro lado, se lo he explicado porque me lo ha preguntado en el comentario anterior "¿Estructura del problema o estructura de datos? ¿Qué es un módulo? ¿Ya sabes que va a ser una estructura de datos? ¿Ya sabes que va a ser para los "ejercicios"?" y para que observe que entiendo lo que estoy escribiendo.

2024-11-04 16:11 UTC, JJ commented on docs/config-milestones.md
> ++ **Descripción:** **Módulo que defina la estructura de datos** que va almacenar los ejercicios para la obtención de rutinas y la interfaz del mismo, sin implementación.
> Pero profesor, ¿porque no es útil lo que he escrito? literalmente me he basado en su video explicativo de la definición de [producto mínimamente viable/milestone](https://www.youtube.com/watch?v=aEBv4dT7UGc&t=4s) y justamente pone de ejemplo el milestone 0 que necesito en mi problema especifico. Ademas de que se entiende perfectamente la necesidad de un diseño de estructura del problema inicial, antes de comenzar con el código.

No te entiendo, ¿qué quieres decir con esto? Si lo que quieres decir es que mi vídeo está mal, es enteramente posible.

2024-11-04 16:12 UTC, JJ commented on docs/config-milestones.md
> ++ **Descripción:** **Módulo que defina la estructura de datos** que va almacenar los ejercicios para la obtención de rutinas y la interfaz del mismo, sin implementación.
> Por otro lado, se lo he explicado porque me lo ha preguntado en el comentario anterior "¿Estructura del problema o estructura de datos? ¿Qué es un módulo? ¿Ya sabes que va a ser una estructura de datos? ¿Ya sabes que va a ser para los "ejercicios"?" y para que observe que entiendo lo que estoy escribiendo.

Creo que a estas alturas deberíais entender que cuando hago alguna pregunta es para que, a través de la respuesta, consideréis posibilidades diferentes a lo que habéis escrito que os permitan entender mejor lo que estáis haciendo.

2024-11-04 16:17 UTC, JJ commented on docs/config-milestones.md
> ++ **Hus asociadas** HU001.
> Soy consciente de que en el fichero de errores frecuentes explica que no se debe mencionar las Hus asociadas 

Sería conveniente que tratárais de leer lo que pone, porque como os pido precisión en vuestra entrega, también trato de ser preciso en lo que escribo. Por favor, lee lo que dice *literalmente* a ver si usa *mencionar* u otra palabra.

> pero, la verdad es que me siento confundida porque en el archivo de referencia para la explicación del [objetivo 1](https://jj.github.io/IV/documentos/proyecto/1.Planificacion) menciona literalmente "Alguna **HUs tendrá que asignarse al siguiente milestone, aunque se podrán ir moviendo durante el avance del proyecto; de esta forma se prioriza una HU frente a las otras para comenzar a desarrollar**", ademas de, " Hay que desarrollar la idea en 

¿En qué se contradice eso con lo que pone en los errores frecuentes?

> de historias de usuario (HU). Se crearán también los hitos (milestones) iniciales en el desarrollo, y **habrá que asignar alguna HU al milestone 0 para poder comenzar a trabajar en el objetivo siguiente.**" y en la lista de 

¿En qué se contradice eso con lo que dice literalmente en los errores frecuentes?

> comprobación del objetivo 1, uno de ellos dice textualmente "**¿El milestone 0 tiene asignada alguna historia de usuario?**"

Insisto, ¿en qué se contradice? Y si se contradijera, ¿qué es lo que no entiendes exactamente?

> 
> Por todo ello, he dejado mencionada la HUs asociada que tiene cada milestone, ya que desde el principio ha sido lo que se ha ido repitiendo...

No, no la has mencionado para nada.  ¿Donde está la mención en

> **Módulo que defina la estructura de datos** que va almacenar los ejercicios para la obtención de rutinas y la interfaz del mismo, sin implementación.

?

2024-11-05 12:52 UTC, mmnuria commented on docs/config-milestones.md
> ++ **Descripción:** **Módulo que defina la estructura de datos** que va almacenar los ejercicios para la obtención de rutinas y la interfaz del mismo, sin implementación.
No profesor, no digo que esté mal el video, solo digo que con su explicación del video me basé para desarrollar las Hus y milestones, si está mal yo no lo sé, pero según me dice, parece que sí. Ya no sé que es lo correcto o lo que no la verdad, estoy muy confundida, considero que según las explicaciones del documento que explica el objetivo 1 donde sugiere la visualización de ese video y todo su contenido (que en varias ocasiones me ha vuelto a decir que me lo lea de nuevo, llevo como 5 veces leidas el documento), lo que he añadido tiene que ser correcto, si no lo es, necesitaría alguna orientación más específica porfavor, llevo casi 5 semanas con este objetivo, intentando día a día superarlo, aprendiendo de mis errores y entendiendo cada paso que realizo, pero ya no sé que más hacer de verdad...

2024-11-05 12:56 UTC, mmnuria commented on docs/config-milestones.md
> ++ **Hus asociadas** HU001.
En el momento en el que escribo "Hus asociadas = HU001" estoy mencionando la Hu asociada al milestone 0 (en este caso).

Si se refiere que no escriba "Hus asociadas" entonces como debo ponerlo?

2024-11-05 13:27 UTC, JJ commented on docs/config-milestones.md
> ++ **Descripción:** **Módulo que defina la estructura de datos** que va almacenar los ejercicios para la obtención de rutinas y la interfaz del mismo, sin implementación.
No, lo estoy diciendo yo. Lo que tienes que entender es que no se trata de resumir lo que has visto en algún otro lugar. Se trata de que hagas un documento que se pueda usar como base para un desarrollo de una aplicación.

2024-11-05 13:28 UTC, JJ commented on docs/config-milestones.md
> ++ **Hus asociadas** HU001.
¿Me estás pidiendo que te diga como tienes que hacer las cosas? ¿Entiendes que lo que yo hago es evaluar lo que haces y sugerirte mejoras para que entiendas mejor conceptos? Si yo te dijera qué tienes que hacer, ¿qué es lo que quedaría por evaluar? ¿Que lo has escrito sin faltas de ortografía?

2024-11-07 09:04 UTC, mmnuria commented
@JJ Esperando revisión.

2024-11-07 09:31 UTC, JJ approved these changes
👏

2024-11-07 09:51 UTC, merged